name: Bug Report
description: File a bug report to help us improve cJSON-Tools
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version of cJSON-Tools
          required: true
        - label: I have included all necessary information to reproduce the issue
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - C Library
        - Python Bindings
        - Build System
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows 10/11
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of cJSON-Tools are you using?
      placeholder: "e.g., 1.4.0, latest from main branch"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Install cJSON-Tools with '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: input_data
    attributes:
      label: Input Data
      description: Sample JSON data that triggers the issue (if applicable)
      placeholder: |
        ```json
        {
          "example": "data"
        }
        ```

  - type: textarea
    id: error_output
    attributes:
      label: Error Output
      description: Any error messages or stack traces
      placeholder: |
        ```
        Paste error output here...
        ```

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - Python version: 3.11.0
        - Compiler: GCC 11.2.0
        - Memory: 16GB
        - CPU: Intel i7-10700K
        - Any other relevant details...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or files that might help...
