name: Feature Request
description: Suggest a new feature or enhancement for cJSON-Tools
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please provide detailed information about your feature request to help us understand and evaluate it.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have considered if this feature aligns with the project's goals
          required: true
        - label: I have provided sufficient detail for the feature to be understood
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Performance Optimization
        - New Functionality
        - API Enhancement
        - Developer Experience
        - Documentation
        - Build/CI Improvement
        - Security Enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: Summarize your feature request in 1-2 sentences...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're facing:
        - What are you trying to accomplish?
        - What's currently preventing you from doing it?
        - How does this impact your workflow?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: |
        Describe how you envision this feature working:
        - What would the API look like?
        - How would users interact with it?
        - What would the expected behavior be?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        Describe any alternative solutions or workarounds you've considered:
        - Other ways to solve the same problem
        - Existing tools or libraries that provide similar functionality
        - Workarounds you're currently using

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```python
        # Example Python usage
        import cjson_tools
        
        # Your proposed API usage here
        result = cjson_tools.new_feature(data, options)
        ```
        
        ```bash
        # Example C library usage
        ./bin/json_tools --new-feature input.json
        ```

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Performance improvements
        - Better user experience
        - Increased functionality
        - Compatibility with other tools
        - etc.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Any thoughts on implementation details or challenges?
      placeholder: |
        - Potential implementation approaches
        - Technical challenges or considerations
        - Impact on existing functionality
        - Performance implications
        - Breaking changes (if any)

  - type: textarea
    id: testing
    attributes:
      label: Testing Strategy
      description: How should this feature be tested?
      placeholder: |
        - Unit tests needed
        - Integration tests
        - Performance benchmarks
        - Edge cases to consider

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide domain expertise/guidance

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references
      placeholder: |
        - Links to similar features in other projects
        - Research or benchmarks supporting the feature
        - Screenshots or mockups (if applicable)
        - Any other relevant information
